WITH T2_GRADE_SCORE AS(
SELECT *, CASE WHEN GRADE = 'A' THEN 50 WHEN GRADE = 'B' THEN 40 WHEN GRADE = 'C' THEN 30 WHEN GRADE = 'D' THEN 20 WHEN GRADE = 'E' THEN 10 ELSE 0 END GRADE_SCORE FROM PD2023_W25_OUTPUT
),
T2_GRADE_SCORE_PIVOT AS(
SELECT * FROM(
SELECT STUDENT_ID::INT AS STUDENT_ID, FULL_NAME, DATE_OF_BIRTH, REGION, SUBJECT, ARRAY_CONSTRUCT(MIN(GRADE), SUM(GRADE_SCORE)) S FROM T2_GRADE_SCORE GROUP BY STUDENT_ID, FULL_NAME, DATE_OF_BIRTH, SUBJECT, REGION) PIVOT(ARRAY_AGG(S) FOR SUBJECT IN ('English', 'Maths', 'Science')) p (STUDENT_ID, FULL_NAME, DATE_OF_BIRTH, REGION, ENGLISH, MATHS, SCIENCE)
)
SELECT sl.*, c.* exclude STUDENT_ID FROM(
SELECT * exclude (ENGLISH, MATHS, SCIENCE), REPLACE(ENGLISH[0][0], '"') AS ENGLISH, REPLACE(MATHS[0][0], '"') AS MATHS, REPLACE(SCIENCE[0][0], '"') AS SCIENCE, ENGLISH[0][1] + MATHS[0][1] + SCIENCE[0][1] AS GRADE_SCORE FROM T2_GRADE_SCORE_PIVOT) AS c JOIN PD2023_SCHOOL_LOOKUP AS sl ON c.STUDENT_ID = sl.STUDENT_ID
);