WITH ATTENDANCE_SCORE AS(
    SELECT
        ATT.*,
        TS.* exclude STUDENT_NAME
    FROM
        TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK22_ATTENDANCE_FIGURES AS ATT
        JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK22_STUDENT_TEST_SCORES AS TS ON ATT.STUDENT_NAME = TS.STUDENT_NAME
),
CORRECT_SPELLING AS(
    SELECT
        * exclude COL_NAME,
        NORMARLISE_ED_DIST(SUBJECT, SUBJECT_NAME) AS SCORE
    FROM(
            SELECT
                'Math' AS M,
                'Science' AS S,
                'English' AS E
        ) UNPIVOT (SUBJECT_NAME FOR COL_NAME IN (M, S, E)) AS t1
        CROSS JOIN ATTENDANCE_SCORE AS t2
    WHERE
        SCORE < 0.2
)
SELECT
    CASE
        WHEN ATTENDANCE_PERCENTAGE < 0.7 THEN 'Low Attendance'
        WHEN ATTENDANCE_PERCENTAGE > 0.9 THEN 'High Attendance'
        ELSE 'Medium Attendance'
    END AS ATTENDANCE_FLAG,
    REPLACE(SPLIT(STUDENT_NAME, '_') [0], '"', '') AS FIRST_NAME,
    REPLACE(SPLIT(STUDENT_NAME, '_') [1], '"', '') AS SURNAME,
    SUBJECT_NAME AS SUBJECT,
    * exclude (
        SUBJECT,
        SUBJECT_NAME,
        STUDENT_NAME,
        TEST_DATE,
        SCORE
    ),
    ROUND(TEST_SCORE, 0) AS TEST_SCORE_INTEGER
FROM
