WITH SCORE_RANGE AS(
SELECT
    * exclude (ENGLISH, ECONOMICS, PSYCHOLOGY),
    NTILE(4) OVER(
        ORDER BY
            ENGLISH DESC
    ) AS ENGLISH,
    NTILE(4) OVER(
        ORDER BY
            ECONOMICS DESC
    ) AS ECONOMICS,
    NTILE(4) OVER(
        ORDER BY PSYCHOLOGY DESC
    ) AS PSYCHOLOGY
FROM
    TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK23_RESULTS
),
STUDENT_SCORE AS(
SELECT STUDENT_ID, SUBJECT, RANGE FROM(
SELECT * FROM SCORE_RANGE UNPIVOT(SCORE FOR SUBJECT IN (ENGLISH, ECONOMICS, PSYCHOLOGY))) AS p LEFT JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK24_TILES AS t ON p.SCORE = t.NUMBER
)
SELECT FULL_NAME, CLASS, ENGLISH, ECONOMICS, PSYCHOLOGY FROM(
SELECT * FROM STUDENT_SCORE AS s JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK23_STUDENT_INFO AS i ON s.STUDENT_ID = i.X_STUDENT_ID) PIVOT(MIN(RANGE) FOR SUBJECT IN ('ENGLISH', 'ECONOMICS', 'PSYCHOLOGY')) AS p(STUDENT_ID, X_STUDENT_ID, FULL_NAME, GENDER, CLASS, ENGLISH, ECONOMICS, PSYCHOLOGY) WHERE REGEXP_COUNT(CONCAT_WS('-', ENGLISH, ECONOMICS, PSYCHOLOGY), '25th percentile') >= 2 AND ( CLASS LIKE '%9A%' OR  CLASS LIKE '%9B%');

